public class Constants {
    public static final String CONTACT_LEVEL_VALUE_PRIMARY = 'Primary';
    public static final String CONTACT_LEVEL_VALUE_SECONDARY = 'Secondary';
    public static final String CONTACT_LEVEL_VALUE_TERTIARY = 'Tertiary';
    public static final String CASE_PRIORITY_VALUE_HIGH = 'High';
    public static final String CASE_PRIORITY_VALUE_MEDIUM = 'Medium';
    public static final String CASE_PRIORITY_VALUE_LOW = 'Low';
    public static final String CASE_STATUS_VALUE_WORKING = 'Working';
    public static final String CASE_ORIGIN_VALUE_NEW_CONTACT = 'New Contact';
    public static final String ERROR_CREATING_NEW_CONTACT = 'Error creating new contact.';
    public static final String SUCCESSFULLY_CREATED_NEW_CONTACT = 'successfully created.';
}